spring.application.name=info_sharing_app

# PostgreSQLの設定
spring.datasource.url=jdbc:postgresql://localhost:5432/info_sharing
spring.datasource.username=hogeuser
spring.datasource.password=hoge
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always

# ページの設定
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# 404エラー時にリダイレクトするページを指定
server.error.path=/error
# 404エラーを発生させた場合に返すビューの設定（任意）
server.error.whitelabel.enabled=false